name: shimmer_alternative
description: A Flutter package to show shimmer effect while loading cards, containers, text, and text fields.
version: 0.0.7+2
homepage: https://github.com/protheeuz/shimmer-alternative
repository: https://github.com/protheeuz/shimmer-alternative

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  assets:
    - assets/qr_code.png
    - assets/paypal_qr_code.png

topics:
  - shimmer
  - loading
  - skeleton
  - flutter
  - animation
